env:
  local:
    server:
      port: 8080
    database:
      name: hybrid
      host: localhost
      port: 5432
      user: postgres
      password: postgres
    gmail:
      user: hybridsonnh@gmail.com
      password: 123456789Hson 